version: '3.3'
services:
  app:
    image: events_app-img
    build: .
    container_name: 'events_app_c'
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - .:/events_app
      - ./node_modules
    stdin_open: true
    tty: true  
