import Head from "next/head"
import Layout from "../layout/layout"
import Link from "next/link"
import styles from "../styles/Form.module.css"
import Image from "next/image"
import { HiAtSymbol, HiFingerPrint } from "react-icons/hi"
import { useState } from "react"
import { signIn } from "next-auth/react"
import { useForm } from "react-hook-form"
import { useRouter } from "next/router"

export default function Login() {
  const [show, setShow] = useState(false)
  const router = useRouter()

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm()

  // credentials
  const onSubmit = async ({ email, password }: any) => {
    const status: any = await signIn("credentials", {
      redirect: false,
      email: email,
      password: password,
      callbackUrl: "/",
    })

    if (status.ok) {
      router.push(status.url)
    }
  }

  // google
  const handleGoogleSignin = async () => {
    signIn("google", { callbackUrl: "http://localhost:3000" })
  }
  const handleGithubSignin = async () => {
    signIn("github", { callbackUrl: "http://localhost:3000" })
  }
  return (
    <Layout>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="flex flex-col w-3/4 gap-10 mx-auto">
        <div className="title">
          <h1 className="py-4 text-4xl font-bold text-gray-800">Explore</h1>
          <p className="w-3/4 mx-auto text-gray-400">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores,
            officia?
          </p>
        </div>

        {/* form */}
        <form className="flex flex-col gap-5" onSubmit={handleSubmit(onSubmit)}>
          <div
            className={`${styles.inputgroup} ${
              errors.email && "border-red-500"
            }`}
          >
            <input
              className={styles.inputtext}
              type="email"
              placeholder="Email"
              {...register("email", { required: true })}
            />
            <span className="flex items-center px-4 icon">
              <HiAtSymbol size={23} />
            </span>
          </div>

          <div
            className={`${styles.inputgroup} ${
              errors.password && "border-red-500"
            }`}
          >
            <input
              className={styles.inputtext}
              type={show ? "text" : "password"}
              placeholder="Password"
              {...register("password", { required: true })}
            />
            <span
              className="icon flex cursor-pointer items-center px-4 hover:text-[#6366f1]"
              onClick={() => setShow((prevSt) => !prevSt)}
            >
              <HiFingerPrint size={23} />
            </span>
          </div>

          {/* login buttons */}
          <div className="input-button">
            <button className={styles.button} type="submit">
              Login
            </button>
          </div>
          <div className="input-button">
            <button
              className={styles.button_custom}
              type="button"
              onClick={handleGoogleSignin}
            >
              Sign In with Google{" "}
              <Image
                src={"/images/google.svg"}
                width="20"
                height={20}
                alt="google"
              />
            </button>
          </div>
          <div className="input-button">
            <button
              className={styles.button_custom}
              type="button"
              onClick={handleGithubSignin}
            >
              Sign In with Github{" "}
              <Image
                src={"/images/github.svg"}
                width="20"
                height={20}
                alt="github"
              />
            </button>
          </div>
        </form>

        {/* button */}
        <p className="text-center text-gray-400 ">
          Don`t have an account yet?{" "}
          <Link href={"/register"}>
            <a className="text-blue-700">Sign Up</a>
          </Link>
        </p>
      </section>
    </Layout>
  )
}
